In [1]:
class Vehicle:
    name = ""
    kind = "car"
    color = ""
    value = 100.00
    def description(self):
        desc_str = "%s is a %s %s worth $%.2f." % (self.name, self.color, self.kind, self.value)
        return desc_str


car1 = Vehicle()
car1.name = "Fer"
car1.color = "red"
car1.kind = "convertible"
car1.value = 60000.00

car2 = Vehicle()
car2.name = "Jump"
car2.color = "blue"
car2.kind = "van"
car2.value = 10000.00


print(car1.description())
print(car2.description())

Fer is a red convertible worth $60000.00.
Jump is a blue van worth $10000.00.


This is my code for classes and objects. It was part of the Learn Python Tutorials 2. I was tasked to create two new vehicles called car1 and car2. I then set car1 to be a red convertible worth $60,000.00 with a name of Fer. After I set car2 to be a blue van named Jump worth $10,000.00.

